Repository testit-tms/adapters-java, pull requests merged in 2022-09, with the labels that each got.

#37 Added config file validation
  testit-java-commons/src/main/java/ru/testit/properties/AppProperties.java
Labels: enhancement

#39 Added overload for addAttachments
  testit-adapter-junit4/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-junit4/src/test/java/ru/testit/samples/failed/SampleTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/FullBeforeAfterTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterEachTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/OnlyBeforeAfterEachTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
  testit-java-commons/src/main/java/ru/testit/services/Adapter.java
Labels: enhancement

#40 Removed required annotations
  testit-adapter-junit4/Readme.md
  testit-adapter-junit4/src/main/java/ru/testit/listener/Utils.java
  testit-adapter-junit5/Readme.md
  testit-adapter-testng/Readme.md
  testit-java-commons/src/main/java/ru/testit/services/Utils.java
  testit-java-commons/src/test/java/ru/testit/services/UtilsTest.java
Labels: enhancement

#41 Updated documentation
  testit-adapter-junit4/Readme.md
  testit-adapter-junit5/Readme.md
  testit-adapter-testng/Readme.md
Labels: documentation

#42 Refactored adapter's configurator
  testit-adapter-junit4/Readme.md
  testit-adapter-junit4/build.gradle.kts
  testit-adapter-junit4/src/main/java/ru/testit/listener/BaseJunit4Listener.java
  testit-adapter-junit4/src/main/java/ru/testit/listener/BaseJunit4Runner.java
  testit-adapter-junit4/src/test/resources/testit.properties
  testit-adapter-junit5/Readme.md
  testit-adapter-junit5/build.gradle.kts
  testit-adapter-junit5/src/test/resources/testit.properties
  testit-adapter-testng/Readme.md
  testit-adapter-testng/build.gradle.kts
  testit-adapter-testng/src/test/resources/testit.properties
  testit-java-commons/src/main/java/ru/testit/clients/ClientConfiguration.java
  testit-java-commons/src/main/java/ru/testit/properties/AdapterConfig.java
  testit-java-commons/src/main/java/ru/testit/properties/AppProperties.java
  testit-java-commons/src/main/java/ru/testit/services/ExecutableTest.java
  testit-java-commons/src/main/java/ru/testit/writers/HttpWriter.java
  testit-java-commons/src/test/java/ru/testit/writers/HttpWriterTest.java
Labels: documentation, enhancement

#43 Updated documentations
  gradle.properties
  testit-adapter-junit4/Readme.md
  testit-adapter-junit5/Readme.md
  testit-adapter-testng/Readme.md
Labels: documentation

#45 Fixed filters
  testit-adapter-junit4/src/main/java/ru/testit/listener/BaseJunit4Listener.java
  testit-adapter-junit5/src/main/java/ru/testit/listener/BaseJunit5Listener.java
  testit-adapter-junit5/src/main/java/ru/testit/listener/Junit5PostDiscoveryFilter.java
  testit-adapter-testng/src/main/java/ru/testit/listener/BaseTestNgListener.java
Labels: bug

#47 Fixed review comments
  testit-java-commons/src/main/java/ru/testit/services/Adapter.java
Labels: bug

#48 Update Readme.md
  testit-adapter-junit5/Readme.md
Labels: documentation
