Repository testit-tms/adapters-java, pull requests merged in 2022-12, with the labels that each got.

#67 Added listener before stop test case
  gradle.properties
  testit-adapter-cucumber4/Readme.md
  testit-adapter-cucumber5/Readme.md
  testit-adapter-cucumber6/Readme.md
  testit-adapter-cucumber7/Readme.md
  testit-adapter-jbehave/Readme.md
  testit-adapter-jbehave/src/main/java/ru/testit/listener/BaseJbehaveListener.java
  testit-adapter-junit4/Readme.md
  testit-adapter-junit5/Readme.md
  testit-adapter-testng/Readme.md
  testit-java-commons/Readme.md
  testit-java-commons/src/main/java/ru/testit/listener/AdapterListener.java
  testit-java-commons/src/main/java/ru/testit/listener/DefaultListener.java
  testit-java-commons/src/main/java/ru/testit/listener/ListenerManager.java
  testit-java-commons/src/main/java/ru/testit/listener/ServiceLoaderListener.java
  testit-java-commons/src/main/java/ru/testit/services/Adapter.java
  testit-java-commons/src/main/java/ru/testit/services/AdapterManager.java
  testit-java-commons/src/test/java/ru/testit/services/AdapterManagerTest.java
Labels: enhancement

#68 Updated documentation.
  testit-adapter-junit4/Readme.md
  testit-adapter-junit4/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-junit4/src/test/java/ru/testit/samples/failed/SampleTests.java
  testit-adapter-junit5/Readme.md
  testit-adapter-junit5/src/test/java/ru/testit/samples/FullBeforeAfterTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterEachTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
  testit-adapter-testng/Readme.md
  testit-adapter-testng/src/test/java/ru/testit/samples/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/OnlyBeforeAfterEachTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
Labels: documentation

#69 Fixed exception for Junit5
  gradle.properties
  testit-adapter-junit5/src/main/java/ru/testit/listener/BaseJunit5Listener.java
Labels: bug
