Repository testit-tms/adapters-java, pull requests merged in 2022-08, with the labels that each got.

#28 Added unit tests for ResultStorage.
  testit-java-commons/src/main/java/ru/testit/services/ResultStorage.java
  testit-java-commons/src/test/java/ru/testit/services/ResultStorageTest.java
Labels: tests

#30 Fixed bug with java version
  build.gradle.kts
  gradle.properties
Labels: bug

#32 Added WorkItemIds annotation
  testit-adapter-junit4/Readme.md
  testit-adapter-junit4/src/main/java/ru/testit/listener/Utils.java
  testit-adapter-junit4/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-junit4/src/test/java/ru/testit/samples/failed/SampleTests.java
  testit-adapter-junit5/Readme.md
  testit-adapter-junit5/src/test/java/ru/testit/samples/FullBeforeAfterTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterEachTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/ParameterizedTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
  testit-adapter-testng/Readme.md
  testit-adapter-testng/src/test/java/ru/testit/samples/DataProviderParameterizedTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/OnlyBeforeAfterEachTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/XmlParameterizedTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
  testit-java-commons/src/main/java/ru/testit/annotations/WorkItemId.java
  testit-java-commons/src/main/java/ru/testit/annotations/WorkItemIds.java
  testit-java-commons/src/main/java/ru/testit/models/TestResult.java
  testit-java-commons/src/main/java/ru/testit/services/Utils.java
  testit-java-commons/src/main/java/ru/testit/writers/HttpWriter.java
  testit-java-commons/src/test/java/ru/testit/Helper.java
  testit-java-commons/src/test/java/ru/testit/services/UtilsTest.java
  testit-java-commons/src/test/java/ru/testit/writers/HttpWriterTest.java
Labels: enhancement

#33 Made "Title" and "Description" annotations as optional
  testit-adapter-junit4/src/main/java/ru/testit/listener/Utils.java
  testit-java-commons/src/main/java/ru/testit/services/Utils.java
  testit-java-commons/src/test/java/ru/testit/services/UtilsTest.java
Labels: enhancement

#34 Fixed writer logic
  testit-java-commons/src/main/java/ru/testit/writers/Converter.java
  testit-java-commons/src/main/java/ru/testit/writers/HttpWriter.java
  testit-java-commons/src/test/java/ru/testit/writers/HttpWriterTest.java
Labels: bug

#35 Added filters to TestNG and JUnit5
  gradle.properties
  testit-adapter-junit5/Readme.md
  testit-adapter-junit5/build.gradle.kts
  testit-adapter-junit5/src/main/java/ru/testit/listener/Junit5PostDiscoveryFilter.java
  testit-adapter-junit5/src/main/services/org.junit.platform.launcher.PostDiscoveryFilter
  testit-adapter-junit5/src/test/resources/META-INF/services/org.junit.platform.launcher.PostDiscoveryFilter
  testit-adapter-junit5/src/test/resources/testit.properties
  testit-adapter-testng/Readme.md
  testit-adapter-testng/src/main/java/ru/testit/listener/BaseTestNgListener.java
  testit-adapter-testng/src/test/resources/testit.properties
  testit-adapter-testng/src/test/resources/testng.xml
  testit-java-commons/src/main/java/ru/testit/clients/ApiClient.java
  testit-java-commons/src/main/java/ru/testit/clients/TmsApiClient.java
  testit-java-commons/src/main/java/ru/testit/properties/AdapterConfig.java
  testit-java-commons/src/main/java/ru/testit/properties/AdapterMode.java
  testit-java-commons/src/main/java/ru/testit/services/Adapter.java
  testit-java-commons/src/main/java/ru/testit/services/AdapterManager.java
  testit-java-commons/src/main/java/ru/testit/services/ConfigManager.java
  testit-java-commons/src/test/java/ru/testit/services/AdapterManagerTest.java
Labels: documentation, enhancement

#36 Refactored adapter logic
  testit-adapter-junit5/Readme.md
  testit-adapter-junit5/src/main/java/ru/testit/listener/Junit5PostDiscoveryFilter.java
  testit-adapter-testng/src/main/java/ru/testit/listener/BaseTestNgListener.java
  testit-java-commons/src/main/java/ru/testit/models/ClassContainer.java
  testit-java-commons/src/main/java/ru/testit/models/FixtureResult.java
  testit-java-commons/src/main/java/ru/testit/models/MainContainer.java
  testit-java-commons/src/main/java/ru/testit/models/ResultWithSteps.java
  testit-java-commons/src/main/java/ru/testit/models/StepResult.java
  testit-java-commons/src/main/java/ru/testit/models/TestResult.java
  testit-java-commons/src/main/java/ru/testit/services/AdapterManager.java
  testit-java-commons/src/main/java/ru/testit/services/ResultStorage.java
  testit-java-commons/src/main/java/ru/testit/writers/Converter.java
  testit-java-commons/src/main/java/ru/testit/writers/HttpWriter.java
  testit-java-commons/src/test/java/ru/testit/Helper.java
  testit-java-commons/src/test/java/ru/testit/services/AdapterManagerTest.java
  testit-java-commons/src/test/java/ru/testit/services/ResultStorageTest.java
  testit-java-commons/src/test/java/ru/testit/writers/HttpWriterTest.java
Labels: enhancement
