Repository testit-tms/adapters-java, pull requests merged in 2023-05, with the labels that each got.

#87 Updated documentation.
  testit-adapter-cucumber4/Readme.md
  testit-adapter-cucumber5/Readme.md
  testit-adapter-cucumber6/Readme.md
  testit-adapter-cucumber7/Readme.md
  testit-adapter-jbehave/Readme.md
  testit-adapter-junit4/Readme.md
  testit-adapter-junit5/Readme.md
  testit-adapter-testng/Readme.md
Labels: documentation

#88 Fixed dropping the "isFlaky" flag.
  gradle.properties
  testit-java-commons/src/main/java/ru/testit/writers/HttpWriter.java
Labels: bug

#89 Fixed test extractExternalID_WithoutExternalID
  testit-java-commons/src/test/java/ru/testit/services/UtilsTest.java
Labels: tests
