Repository testit-tms/adapters-java, pull requests merged in 2024-05, with the labels that each got.

#138 Fix unit tests
  build.gradle.kts
  testit-adapter-cucumber4/Readme.md
  testit-adapter-cucumber4/build.gradle.kts
  testit-adapter-cucumber4/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-cucumber4/src/test/resources/testit.properties
  testit-adapter-cucumber5/Readme.md
  testit-adapter-cucumber5/build.gradle.kts
  testit-adapter-cucumber5/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-cucumber6/Readme.md
  testit-adapter-cucumber6/build.gradle.kts
  testit-adapter-cucumber6/src/main/java/ru/testit/listener/ScenarioStorage.java
  testit-adapter-cucumber6/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-cucumber7/Readme.md
  testit-adapter-cucumber7/build.gradle.kts
  testit-adapter-cucumber7/src/main/java/ru/testit/listener/ScenarioParser.java
  testit-adapter-cucumber7/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-jbehave/build.gradle.kts
  testit-adapter-junit4/build.gradle.kts
  testit-adapter-junit4/src/test/java/ru/testit/samples/failed/SampleTests.java
  testit-adapter-junit5/build.gradle.kts
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/OnlyBeforeAfterEachTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/ParameterizedTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-junit5/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
  testit-adapter-selenide/Readme.md
  testit-adapter-selenide/build.gradle.kts
  testit-adapter-selenide/src/test/java/ru/testit/samples/SampleTests.java
  testit-adapter-selenide/src/test/resources/testit.properties
  testit-adapter-testng/build.gradle.kts
  testit-adapter-testng/src/test/java/ru/testit/samples/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/FullBeforeAfterTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterAllTests.java
  testit-adapter-testng/src/test/java/ru/testit/samples/failed/OnlyBeforeAfterEachTests.java
  testit-java-commons/build.gradle.kts
  testit-java-commons/src/main/java/ru/testit/annotations/WorkItemId.java
  testit-java-commons/src/main/java/ru/testit/properties/AppProperties.java
  testit-java-commons/src/main/java/ru/testit/services/ResultStorage.java
  testit-java-commons/src/test/java/ru/testit/Helper.java
  testit-java-commons/src/test/java/ru/testit/services/UtilsHelper.java
  testit-java-commons/src/test/java/ru/testit/writers/HttpWriterTest.java
Labels: tests

#140 Supported TMS 5.0.
  Readme.md
  gradle.properties
  testit-java-commons/build.gradle.kts
  testit-java-commons/src/main/java/ru/testit/clients/ApiClient.java
  testit-java-commons/src/main/java/ru/testit/clients/TmsApiClient.java
  testit-java-commons/src/main/java/ru/testit/writers/Converter.java
  testit-java-commons/src/main/java/ru/testit/writers/HttpWriter.java
  testit-java-commons/src/test/java/ru/testit/Helper.java
  testit-java-commons/src/test/java/ru/testit/writers/HttpWriterTest.java
Labels: documentation, enhancement

#142 Config fix
  gradle.properties
  testit-adapter-cucumber4/Readme.md
  testit-adapter-cucumber4/build.gradle.kts
  testit-adapter-cucumber5/Readme.md
  testit-adapter-cucumber5/build.gradle.kts
  testit-adapter-cucumber6/Readme.md
  testit-adapter-cucumber6/build.gradle.kts
  testit-adapter-cucumber7/Readme.md
  testit-adapter-cucumber7/build.gradle.kts
  testit-adapter-jbehave/Readme.md
  testit-adapter-jbehave/build.gradle.kts
  testit-adapter-junit4/Readme.md
  testit-adapter-junit4/build.gradle.kts
  testit-adapter-junit5/Readme.md
  testit-adapter-junit5/build.gradle.kts
  testit-adapter-selenide/Readme.md
  testit-adapter-selenide/build.gradle.kts
  testit-adapter-testng/Readme.md
  testit-adapter-testng/build.gradle.kts
  testit-java-commons/src/main/java/ru/testit/properties/AppProperties.java
  testit-java-commons/src/main/java/ru/testit/services/AdapterManager.java
Labels: bug

#149 Add Java 17 support
  .github/workflows/gradle.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  gradle.properties
  testit-adapter-cucumber4/Readme.md
  testit-adapter-cucumber5/Readme.md
  testit-adapter-cucumber6/Readme.md
  testit-adapter-cucumber7/Readme.md
  testit-adapter-cucumber7/src/main/java/ru/testit/listener/ScenarioParser.java
  testit-adapter-jbehave/Readme.md
  testit-adapter-jbehave/build.gradle.kts
  testit-adapter-junit4/Readme.md
  testit-adapter-junit4/build.gradle.kts
  testit-adapter-junit5/Readme.md
  testit-adapter-junit5/build.gradle.kts
  testit-adapter-selenide/Readme.md
  testit-adapter-testng/Readme.md
  testit-adapter-testng/build.gradle.kts
  testit-java-commons/build.gradle.kts
Labels: bug, enhancement
